version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: 'datatrain/api'
    IMAGE_TAG: 'staging'
    AWS_ACCOUNT_ID: '802162369613'
# parameter-store:
#   key: "value"
#   key: "value"
# git-credential-helper: yes

phases:
  install:
    runtime-versions:
      nodejs: 8
      docker: 18
    commands:
      - 'yarn install'
      - 'npm run build'
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - $(aws ecr get-login --region us-east-1)
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
