version: 0.2

# env:
# variables:
#   key: "value"
#   key: "value"
# parameter-store:
#   key: "value"
#   key: "value"
# git-credential-helper: yes

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - 'yarn install'
      - 'npm run build'
  build:
    runtime-versions:
      docker: 18
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    runtime-versions:
      docker: 18
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
