version: '3'
services:
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/rmmm/.docker/config.json:/config.json
    command: --interval 30
  app_prod:
    image: dockerhub.ase.in.tum.de:5043/ios19bsh/api:master
    environment:
      PORT: 5000
    ports:
      - 5000:5000
  database_prod:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: init12345
    links:
      - app_prod
  app_dev:
    image: tagged dockerhub.ase.in.tum.de:5043/ios19bsh/api:dev
    environment:
      PORT: 5001
    ports:
      - 5001:5001
  database_dev:
    image: mongo
    links:
      - app_dev
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: init12345
