# THIS DOCKERFILE IS ONLY INTENDED FOR TESTING
version: '3.7'
networks:
  docker-network:
services:
  backend_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 5000
    links:
      - database_dev
    depends_on:
      - database_dev
    ports:
      - '5000:5000'
    networks:
      - docker-network
  database_dev:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: init12345
    networks:
      - docker-network
